### ISSUE TITLE
SSH

### ISSUE THREAD

**Issue by NAlexandrov** [vadimpronin/guacamole-lite#13]
What about SSH? This connection type is not supported?

**Comment by vadimpronin** [comment]
Well, it should be supported, but, to be honest, I've never tested it. 
If you have problems connecting to SSH, could you turn on verbose logging and provide the logs?

**Comment by NAlexandrov** [comment]
RDP works fine. But SSH:
```
[2017-11-23 21:55:20] [Connection 1]  Client connection open
[2017-11-23 21:55:20] [Connection 1]  Token validation failed!
[2017-11-23 21:55:20] [Connection 1]  Closing connection with error:  TypeError: Cannot read property 'includes' of undefined
    at Object.keys.filter.key (/Users/dos/www/r-vision/node_modules/guacamole-lite/lib/ClientConnection.js:134:112)
    at Array.filter (<anonymous>)
    at ClientConnection.mergeConnectionOptions (/Users/dos/www/r-vision/node_modules/guacamole-lite/lib/ClientConnection.js:134:14)
    at new ClientConnection (/Users/dos/www/r-vision/node_modules/guacamole-lite/lib/ClientConnection.js:29:58)
    at Server.newConnection (/Users/dos/www/r-vision/node_modules/guacamole-lite/lib/Server.js:95:59)
    at emitOne (events.js:116:13)
    at WebSocketServer.emit (events.js:211:7)
    at /Users/dos/www/r-vision/node_modules/ws/lib/WebSocketServer.js:91:14
    at completeHybiUpgrade2 (/Users/dos/www/r-vision/node_modules/ws/lib/WebSocketServer.js:284:5)
    at completeHybiUpgrade1 (/Users/dos/www/r-vision/node_modules/ws/lib/WebSocketServer.js:306:13)
[2017-11-23 21:55:20] [Connection 1]  Client connection closed
```

**Comment by vadimpronin** [comment]
Can you also provide your code that you use with guacamole-lite and the token object you send to initiate the connection (if you send any)?
Because from your log I see that the error occurs even before guacamole-lite tries to connect to guacd, so it doesn't look like SSH specific problem.

**Comment by NAlexandrov** [comment]
More details: This code https://github.com/vadimpronin/guacamole-lite/blob/master/lib/ClientConnection.js#L131 try to get item from https://github.com/vadimpronin/guacamole-lite/blob/master/lib/Server.js#L52 and throw an error because this.connectionType = 'ssh';

**Comment by vadimpronin** [comment]
Right, I see. 
The fix should be pretty easy ;) Give me a few minutes

**Comment by vadimpronin** [comment]
v0.5.1 should fix the problem. Could you try it and say if it worked?

**Comment by NAlexandrov** [comment]
I created a token:
```
  connection: {
    type: 'ssh',
    settings: {
      hostname: '10.8.0.24',
      username: 'root',
      password: 'pxtm0222',
    },
  },
```
And tried to connect to:
```
var guac = new Guacamole.Client(
  new Guacamole.WebSocketTunnel('/?token=' + token + '&color-scheme=1&font-name=Arial')
);
```
And got next log:
```
Starting guacamole-lite websocket server
[2017-11-23 22:52:07] [Connection 1]  Client connection open
[2017-11-23 22:52:07] [Connection 1]  Opening guacd connection
[2017-11-23 22:52:07] [Connection 1]  guacd connection open
[2017-11-23 22:52:07] [Connection 1]  Selecting connection type: ssh
[2017-11-23 22:52:07] [Connection 1]  Sending opCode: 6.select,3.ssh;
[2017-11-23 22:52:07] [Connection 1]  <<<W2G< 6.select,3.ssh;***
[2017-11-23 22:52:07] [Connection 1]  Sending opCode: 4.size,9.undefined,9.undefined,9.undefined;
[2017-11-23 22:52:07] [Connection 1]  <<<W2G< 4.size,9.undefined,9.undefined,9.undefined;***
[2017-11-23 22:52:07] [Connection 1]  Sending opCode: 5.audio;
[2017-11-23 22:52:07] [Connection 1]  <<<W2G< 5.audio;***
[2017-11-23 22:52:07] [Connection 1]  Sending opCode: 5.video;
[2017-11-23 22:52:07] [Connection 1]  <<<W2G< 5.video;***
[2017-11-23 22:52:07] [Connection 1]  Sending opCode: 5.image;
[2017-11-23 22:52:07] [Connection 1]  <<<W2G< 5.image;***
[2017-11-23 22:52:07] [Connection 1]  Server sent handshake: 4.args,8.hostname,4.port,8.username,8.password,9.font-name,9.font-size,11.enable-sftp,11.private-key,10.passphrase,12.color-scheme,7.command,15.typescript-path,15.typescript-name,22.create-typescript-path,14.recording-path,14.recording-name,21.create-recording-path,9.read-only
[2017-11-23 22:52:07] [Connection 1]  Sending opCode: 7.connect,9.10.8.0.24,2.22,4.root,8.password,15.Arial?undefined,0.,0.,0.,0.,1.1,0.,0.,0.,0.,0.,0.,0.,0.;
[2017-11-23 22:52:07] [Connection 1]  <<<W2G< 7.connect,9.10.8.0.24,2.22,4.root,8.password,15.Arial?undefined,0.,0.,0.,0.,1.1,0.,0.,0.,0.,0.,0.,0.,0.;***
open
[2017-11-23 22:52:08] [Connection 1]  >>>G2W> 5.ready,37.$a3449004-e8c9-4e5f-a593-725b28439071;###
[2017-11-23 22:52:12] [Connection 1]  <<<W2G< 3.nop;***
[2017-11-23 22:52:12] [Connection 1]  Closing guacd connection
close
[2017-11-23 22:52:12] [Connection 1]  Client connection closed
```

**Comment by vadimpronin** [comment]
Well, I see a few possible problems:
```
[2017-11-23 22:52:07] [Connection 1]  Sending opCode: 4.size,9.undefined,9.undefined,9.undefined;
[2017-11-23 22:52:07] [Connection 1]  <<<W2G< 4.size,9.undefined,9.undefined,9.undefined;***
```
The 'undefined' parameters are the width, height and dpi. I don't really understand how they could be used in ssh sessions but seems like guacamole protocol requires them. You can add them to your settings or upgrade to 0.5.2 where I've predefined defaults.

Another possible reason could be here:
```
[2017-11-23 22:52:07] [Connection 1]  Sending opCode: 7.connect,9.10.8.0.24,2.22,4.root,8.password,15.Arial?undefined,0.,0.,0.,0.,1.1,0.,0.,0.,0.,0.,0.,0.,0.;
```

'15.Arial?undefined' doesn't look normal and I don't really see how '?undefined' could appear there. But anyway, first I would try omitting both 'color-scheme' and 'font-name' in your query to see if ssh protocol works at all.
Anyhow, color-scheme=1 is incorrect value. Correct ones are: black-white, gray-black, green-black, white-black. Check the possible values and defaults here http://guacamole.incubator.apache.org/doc/gug/configuring-guacamole.html#ssh

**Comment by NAlexandrov** [comment]
All works fine! Thank you!

P.S. ```?undefined``` come from here:

index.html
```
var guac = new Guacamole.Client(
  new Guacamole.WebSocketTunnel('/?token=' + token)
);

...

// Connect
guac.connect();
```

connect() method has optional argument data: http://guacamole.incubator.apache.org/doc/guacamole-common-js/Tunnel.js.html#line40

but in http://guacamole.incubator.apache.org/doc/guacamole-common-js/Tunnel.js.html#line751 you can see the next code:

```
        // Connect socket
        socket = new WebSocket(tunnelURL + "?" + data, "guacamole");
```

so guacamole-lite in https://github.com/vadimpronin/guacamole-lite/blob/master/lib/ClientConnection.js#L19 try parse string with ?undefined

so if I change from ```guac.connect();``` to ```guac.connect('');``` all works fine without undefined

**Comment by vadimpronin** [comment]
Good to hear it worked! And thanks for the hint with guac.connect()
I'm closing the issue. Feel free to reopen or open a new one if you'll encounter further problems

**Comment by Dshufeng** [comment]
In fact,there's a better way.I have it.
```
var guac = new Guacamole.Client(
      new Guacamole.WebSocketTunnel("ws://ip:port")
);
guac.connect('token=' + token);
```
