### ISSUE TITLE
Facing: guacd was inactive for too long

### ISSUE THREAD

**Issue by naureen-34** [vadimpronin/guacamole-lite#35]
Hi,

We were successfully able to setup guacamole-lite and guacd, the RDP connection was also happening, Though today we are facing "guacd was inactive for too long". 

This is the log:
Starting guacamole-lite websocket server
[2020-08-20 12:19:05] [Connection 1]  Client connection open
[2020-08-20 12:19:05] [Connection 1]  Opening guacd connection
[2020-08-20 12:19:05] [Connection 1]  guacd connection open
[2020-08-20 12:19:05] [Connection 1]  Selecting connection type: rdp
[2020-08-20 12:19:05] [Connection 1]  Sending opCode: 6.select,3.rdp;
[2020-08-20 12:19:05] [Connection 1]  <<<W2G< 6.select,3.rdp;***
[2020-08-20 12:19:05] [Connection 1]  Sending opCode: 4.size,6.1100px,6.500px?,2.96;
[2020-08-20 12:19:05] [Connection 1]  <<<W2G< 4.size,6.1100px,6.500px?,2.96;***
[2020-08-20 12:19:05] [Connection 1]  Sending opCode: 5.audio,9.audio/L16;
[2020-08-20 12:19:05] [Connection 1]  <<<W2G< 5.audio,9.audio/L16;***
[2020-08-20 12:19:05] [Connection 1]  Sending opCode: 5.video;
[2020-08-20 12:19:05] [Connection 1]  <<<W2G< 5.video;***
[2020-08-20 12:19:05] [Connection 1]  Sending opCode: 5.image;
[2020-08-20 12:19:05] [Connection 1]  <<<W2G< 5.image;***
[2020-08-20 12:19:05] [Connection 1]  Server sent handshake: .....
[2020-08-20 12:19:05] [Connection 1]  Sending opCode: 7.......;
[2020-08-20 12:19:05] [Connection 1]  <<<W2G< 7.connect,...,0.,.....;***
[2020-08-20 12:19:05] [Connection 1]  >>>G2W> 5.ready,37......;###
[2020-08-20 12:19:05] [Connection 1]  <<<W2G< 3.ack,1.1,2.OK,1.0;***
[2020-08-20 12:19:09] [Connection 1]  <<<W2G< 3.nop;***
[2020-08-20 12:19:14] [Connection 1]  <<<W2G< 3.nop;***
[2020-08-20 12:19:16] [Connection 1]  Closing connection with error:  Error: guacd was inactive for too long
    at GuacdClient.checkActivity (/home/ubuntu/node_modules/guacamole-lite/lib/GuacdClient.js:35:41)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
[2020-08-20 12:19:16] [Connection 1]  Closing guacd connection
[2020-08-20 12:19:16] [Connection 1]  Client connection closed

I am passing all params as mentioned here https://github.com/vadimpronin/guacamole-lite/issues/8, omitted them in logs. Already tried restarting guacd and reinstalling guacamole-lite, no luck so far. What am I missing here?

**Comment by naureen-34** [comment]
Resolved: the issue was with the connecting windows machine, it was not connecting.
